# Generated by Django 5.1.3 on 2024-11-17 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saida', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saidas',
            name='preco',
        ),
    ]
