# Generated by Django 5.1.2 on 2024-10-29 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cores',
            options={'verbose_name': 'Cor', 'verbose_name_plural': 'Cores'},
        ),
        migrations.AlterModelOptions(
            name='produtos',
            options={'ordering': ['-produto'], 'verbose_name': 'Produto'},
        ),
    ]
